Aqui vamos analisar um dataset de 20 funcionarios de uma empresa

objetivo:


*   Analisar quais funcionarios estão com **férias em dia** e **férias vencidas**
*   Analisar o **impacto** financeiro que os funcionarios com férias vencidas pode gerar para a empresa
*   Analisar quais setores tem mais funcionarios com **ferias vencidas**

In [ ]:
import pandas as pd

url = '/content/dataset_funcionarios_veman.csv'
df = pd.read_csv(url)
df.head(21)

,nome,idade,cargo,setor,salario,data_admissao,ultima_ferias,status_ferias,anos_ferias_vencidas,tempo_empresa_anos
0,Carlos Silva,37,Técnico Elétrico,Manutenção Elétrica,4612.33,2022-11-06,2025-02-10,1 ano vencido,1,3.5
1,Mariana Souza,23,Técnico Elétrico,Facilities,4132.88,2024-04-20,2024-12-05,1 ano vencido,1,2.0
2,João Pereira,56,Auxiliar de Manutenção,Facilities,2398.84,2020-08-24,2024-08-17,1 ano vencido,1,5.7
3,Fernanda Lima,32,Assistente Administrativo,Manutenção Elétrica,3638.21,2017-07-10,2022-11-15,3 anos vencidos,3,8.8
4,Lucas Martins,43,Assistente Administrativo,Manutenção Hidráulica,2822.97,2024-03-16,2025-09-26,Em dia,0,2.1
5,Patrícia Alves,38,Técnico Elétrico,Administrativo,4771.24,2024-11-12,2022-08-07,3 anos vencidos,3,1.5
6,Rafael Gomes,40,Técnico Elétrico,Operações,3618.20,2018-04-21,2023-07-17,2 anos vencidos,2,8.1
7,Aline Rocha,36,Mecânico,Manutenção Elétrica,3068.74,2016-09-06,2024-03-28,2 anos vencidos,2,9.7
8,Bruno Costa,51,Mecânico,Manutenção Elétrica,3570.19,2018-03-23,2024-02-14,2 anos vencidos,2,8.1
9,Juliana Fernandes,39,Supervisor,Administrativo,5419.01,2017-06-25,2026-01-11,Em dia,0,8.9
10,Thiago Ribeiro,39,Mecânico,Manutenção Hidráulica,3693.39,2018-03-05,2024-10-19,1 ano vencido,1,8.2
11,Amanda Melo,42,Auxiliar de Manutenção,Manutenção Hidráulica,3021.80,2020-11-07,2024-04-04,2 anos vencidos,2,5.5
12,Eduardo Nunes,42,Mecânico,Facilities,4314.55,2022-12-20,2022-10-18,3 anos vencidos,3,3.4
13,Camila Barbosa,37,Gerente,Manutenção Hidráulica,11324.40,2016-12-30,2023-07-13,2 anos vencidos,2,9.4
14,Felipe Carvalho,36,Coordenador,Facilities,7998.50,2023-10-20,2023-03-23,3 anos vencidos,3,2.6
15,Larissa Teixeira,32,Auxiliar de Manutenção,Manutenção Elétrica,2352.84,2016-06-20,2022-07-07,3 anos vencidos,3,9.9
16,Diego Santos,51,Técnico Elétrico,Operações,4072.43,2019-06-02,2023-07-29,2 anos vencidos,2,6.9
17,Vanessa Oliveira,56,Auxiliar de Manutenção,Manutenção Elétrica,2881.71,2016-12-06,2023-06-14,2 anos vencidos,2,9.4
18,Ricardo Moreira,32,Supervisor,Manutenção Elétrica,5587.00,2020-04-06,2025-11-25,Em dia,0,6.1
19,Bianca Araújo,41,Técnico Hidráulico,Facilities,4660.20,2018-03-09,2025-01-15,1 ano vencido,1,8.2

**Ferias em dia**

In [ ]:
df[df['anos_ferias_vencidas'] == 0].groupby(['nome','setor'])['anos_ferias_vencidas'].sum()

nome               setor
Juliana Fernandes  Administrativo           0
Lucas Martins      Manutenção Hidráulica    0
Ricardo Moreira    Manutenção Elétrica      0
Name: anos_ferias_vencidas, dtype: int64

**Ferias vencidas**

In [ ]:
df[df['anos_ferias_vencidas'] > 0].groupby(['nome','cargo'])['anos_ferias_vencidas'].sum().sort_values(ascending=False)

nome              cargo
Eduardo Nunes     Mecânico                     3
Patrícia Alves    Técnico Elétrico             3
Felipe Carvalho   Coordenador                  3
Larissa Teixeira  Auxiliar de Manutenção       3
Fernanda Lima     Assistente Administrativo    3
Aline Rocha       Mecânico                     2
Diego Santos      Técnico Elétrico             2
Amanda Melo       Auxiliar de Manutenção       2
Bruno Costa       Mecânico                     2
Vanessa Oliveira  Auxiliar de Manutenção       2
Rafael Gomes      Técnico Elétrico             2
Camila Barbosa    Gerente                      2
Bianca Araújo     Técnico Hidráulico           1
Carlos Silva      Técnico Elétrico             1
João Pereira      Auxiliar de Manutenção       1
Mariana Souza     Técnico Elétrico             1
Thiago Ribeiro    Mecânico                     1
Name: anos_ferias_vencidas, dtype: int64

vamos calcular as ferias de cada funcionario e descobrir o impacto que cada funcionario com ferias vencidas gera a empresa

In [ ]:
df['ds'] = df['salario'] * 2
df['ut'] = df['ds'] / 3
df['vf'] =  df['anos_ferias_vencidas'] * df['ds'] + df['ut']
df[df['anos_ferias_vencidas'] > 0].groupby(['nome','cargo','anos_ferias_vencidas'])['vf'].sum().sort_values(ascending=False).map('{:,.2f}'.format)

nome              cargo                      anos_ferias_vencidas
Felipe Carvalho   Coordenador                3                       53,323.33
Camila Barbosa    Gerente                    2                       52,847.20
Patrícia Alves    Técnico Elétrico           3                       31,808.27
Eduardo Nunes     Mecânico                   3                       28,763.67
Fernanda Lima     Assistente Administrativo  3                       24,254.73
Diego Santos      Técnico Elétrico           2                       19,004.67
Rafael Gomes      Técnico Elétrico           2                       16,884.93
Bruno Costa       Mecânico                   2                       16,660.89
Larissa Teixeira  Auxiliar de Manutenção     3                       15,685.60
Aline Rocha       Mecânico                   2                       14,320.79
Amanda Melo       Auxiliar de Manutenção     2                       14,101.73
Vanessa Oliveira  Auxiliar de Manutenção     2                       13,447.98
Bianca Araújo     Técnico Hidráulico         1                       12,427.20
Carlos Silva      Técnico Elétrico           1                       12,299.55
Mariana Souza     Técnico Elétrico           1                       11,021.01
Thiago Ribeiro    Mecânico                   1                        9,849.04
João Pereira      Auxiliar de Manutenção     1                        6,396.91
Name: vf, dtype: object

Totalizando

In [ ]:
f"{df[df['anos_ferias_vencidas'] > 0]['vf'].sum():,.2f}"

'353,097.50'

Setor com maior custo em Férias

In [ ]:
df.groupby('setor')['vf'].sum().sort_values(ascending=False).map('{:,.2f}'.format)

setor
Facilities               111,932.12
Manutenção Elétrica      100,394.20
Manutenção Hidráulica     78,679.95
Operações                 35,889.61
Administrativo            35,420.94
Name: vf, dtype: object