Aqui vamos analisar um dataset de 20 funcionarios de uma empresa

objetivo:


*   Analisar quais funcionarios estão com **férias em dia** e **férias vencidas**
*   Analisar o **impacto** financeiro que os funcionarios com férias vencidas pode gerar para a empresa
*   Analisar quais setores tem mais funcionarios com **ferias vencidas**

In [55]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [56]:
import pandas as pd

ferias = pd.read_csv('/content/drive/MyDrive/curriculos/dataset/dataset_funcionarios_veman.csv')
ferias.head(5)

,nome,idade,cargo,setor,salario,data_admissao,ultima_ferias,status_ferias,anos_ferias_vencidas,tempo_empresa_anos
0,Carlos Silva,37,Técnico Elétrico,Manutenção Elétrica,4612.33,2022-11-06,2025-02-10,1 ano vencido,1,3.5
1,Mariana Souza,23,Técnico Elétrico,Facilities,4132.88,2024-04-20,2024-12-05,1 ano vencido,1,2.0
2,João Pereira,56,Auxiliar de Manutenção,Facilities,2398.84,2020-08-24,2024-08-17,1 ano vencido,1,5.7
3,Fernanda Lima,32,Assistente Administrativo,Manutenção Elétrica,3638.21,2017-07-10,2022-11-15,3 anos vencidos,3,8.8
4,Lucas Martins,43,Assistente Administrativo,Manutenção Hidráulica,2822.97,2024-03-16,2025-09-26,Em dia,0,2.1

**Ferias em dia**

In [57]:
ferias[ferias['anos_ferias_vencidas'] == 0].groupby(['nome','setor'])['anos_ferias_vencidas'].sum()

nome               setor
Juliana Fernandes  Administrativo           0
Lucas Martins      Manutenção Hidráulica    0
Ricardo Moreira    Manutenção Elétrica      0
Name: anos_ferias_vencidas, dtype: int64

**Ferias vencidas**

In [58]:
ferias[ferias['anos_ferias_vencidas'] > 0].groupby(['nome','cargo'])['anos_ferias_vencidas'].sum().sort_values(ascending=False)

nome              cargo
Eduardo Nunes     Mecânico                     3
Patrícia Alves    Técnico Elétrico             3
Felipe Carvalho   Coordenador                  3
Larissa Teixeira  Auxiliar de Manutenção       3
Fernanda Lima     Assistente Administrativo    3
Aline Rocha       Mecânico                     2
Diego Santos      Técnico Elétrico             2
Amanda Melo       Auxiliar de Manutenção       2
Bruno Costa       Mecânico                     2
Vanessa Oliveira  Auxiliar de Manutenção       2
Rafael Gomes      Técnico Elétrico             2
Camila Barbosa    Gerente                      2
Bianca Araújo     Técnico Hidráulico           1
Carlos Silva      Técnico Elétrico             1
João Pereira      Auxiliar de Manutenção       1
Mariana Souza     Técnico Elétrico             1
Thiago Ribeiro    Mecânico                     1
Name: anos_ferias_vencidas, dtype: int64

vamos calcular as ferias de cada funcionario e descobrir o impacto que cada funcionario com ferias vencidas gera a empresa

In [75]:
ferias ['Custo das férias'] = ferias['ds'] = ferias['salario'] * 2
ferias ['Custo das férias'] = ferias['ut'] = ferias['ds'] / 3
ferias ['Custo das férias'] = ferias['vf'] =  ferias['anos_ferias_vencidas'] * ferias['ds'] + ferias['ut']
ferias[ferias['anos_ferias_vencidas'] > 0].groupby(['nome','cargo','anos_ferias_vencidas'])['vf'].sum().sort_values(ascending=False).map('{:,.2f}'.format)

nome              cargo                      anos_ferias_vencidas
Felipe Carvalho   Coordenador                3                       53,323.33
Camila Barbosa    Gerente                    2                       52,847.20
Patrícia Alves    Técnico Elétrico           3                       31,808.27
Eduardo Nunes     Mecânico                   3                       28,763.67
Fernanda Lima     Assistente Administrativo  3                       24,254.73
Diego Santos      Técnico Elétrico           2                       19,004.67
Rafael Gomes      Técnico Elétrico           2                       16,884.93
Bruno Costa       Mecânico                   2                       16,660.89
Larissa Teixeira  Auxiliar de Manutenção     3                       15,685.60
Aline Rocha       Mecânico                   2                       14,320.79
Amanda Melo       Auxiliar de Manutenção     2                       14,101.73
Vanessa Oliveira  Auxiliar de Manutenção     2                       13,447.98
Bianca Araújo     Técnico Hidráulico         1                       12,427.20
Carlos Silva      Técnico Elétrico           1                       12,299.55
Mariana Souza     Técnico Elétrico           1                       11,021.01
Thiago Ribeiro    Mecânico                   1                        9,849.04
João Pereira      Auxiliar de Manutenção     1                        6,396.91
Name: vf, dtype: object

Totalizando

In [68]:
f"{ferias[ferias['anos_ferias_vencidas'] > 0]['vf'].sum():,.2f}"

'353,097.50'

In [69]:
ferias ['total custo'] = f"{ferias[ferias['anos_ferias_vencidas'] > 0]['vf'].sum():,.2f}"

Setor com maior custo em Férias

In [70]:
ferias.groupby('setor')['vf'].sum().sort_values(ascending=False).map('{:,.2f}'.format)

setor
Facilities               111,932.12
Manutenção Elétrica      100,394.20
Manutenção Hidráulica     78,679.95
Operações                 35,889.61
Administrativo            35,420.94
Name: vf, dtype: object

In [71]:
ferias ['setor maior custo'] = ferias.groupby('setor')['vf'].sum().sort_values(ascending=False).map('{:,.2f}'.format)

In [77]:
ferias.to_csv('dados_ferias.csv',index = False, sep = ';')
ferias.head()

,nome,idade,cargo,setor,salario,data_admissao,ultima_ferias,status_ferias,anos_ferias_vencidas,tempo_empresa_anos,ds,ut,vf,total custo,setor maior custo,Custo das férias
0,Carlos Silva,37,Técnico Elétrico,Manutenção Elétrica,4612.33,2022-11-06,2025-02-10,1 ano vencido,1,3.5,9224.66,3074.886667,12299.546667,"353,097.50",NaN,12299.546667
1,Mariana Souza,23,Técnico Elétrico,Facilities,4132.88,2024-04-20,2024-12-05,1 ano vencido,1,2.0,8265.76,2755.253333,11021.013333,"353,097.50",NaN,11021.013333
2,João Pereira,56,Auxiliar de Manutenção,Facilities,2398.84,2020-08-24,2024-08-17,1 ano vencido,1,5.7,4797.68,1599.226667,6396.906667,"353,097.50",NaN,6396.906667
3,Fernanda Lima,32,Assistente Administrativo,Manutenção Elétrica,3638.21,2017-07-10,2022-11-15,3 anos vencidos,3,8.8,7276.42,2425.473333,24254.733333,"353,097.50",NaN,24254.733333
4,Lucas Martins,43,Assistente Administrativo,Manutenção Hidráulica,2822.97,2024-03-16,2025-09-26,Em dia,0,2.1,5645.94,1881.980000,1881.980000,"353,097.50",NaN,1881.980000